---
title: "Course Reserves Statistics"
author: "Kevin A Thomas"
date: today
execute: 
  echo: false
  warning: false
  error: false
format: pdf
---

```{r}
# Dependencies
library(dplyr)
library(ggplot2)
library(kableExtra)

# Penn colors
colors_penn <- list(primary = c('#011f5b', '#990000'),
                    secondary = c('#3479be', '#faa755', '#bbd86b', '#bd60a5'),
                    gray = c('#555d6a', '#757f8f', '#a7aeba', '#e1e4ec'))
```

```{r}
# Load data
dat <- read.csv('~/GitHub/course-reserves-stats/res/leganto-usage-views-2026-03-10.csv')
#Replace hard-coded filepath with a dynamic selector in a GUI
dat$Citation <- as.character(dat$Citation)
```

```{r}
# Specify Course.code values (apply to all content)
course_codes <- c('BAN_PUBH-5010-001 202610', 'BAN_PUBH-5010-001 202520', 'BAN_PUBH-5010-001 202510', 'BAN_PUBH-5010-001 202430', 'BAN_PUBH-5010-001 202420', 'BAN_PUBH-5010-001 202410')
#course_codes <- unique(dat$Course.code)
#OR
#Replace hard-coded course_codes with a multi-select GUI that lists available unique Course.code values
```

## Summary by item

```{r}
#User-selectable filters (apply to Summary by item section content only): Course year, Course term for the by-item section only
```

```{r}
# Total student views by item (table)
dat_temp <- dat |>
  filter(Course.code %in% course_codes & User.role == 'Student') |>
  group_by(Citation) |>
  summarize('Maximum\nenrollment' = max(Course.enrollment),
            'Files\ndownloaded' = sum(Files.downloaded),
            'File\nviews' = sum(File.views),
            'Full-text\nviews' = sum(Full.text.views),
            'All\nviews' = sum(Total.views)
            )
kbl(dat_temp,
    format = 'latex',
    caption = 'Number of student views by item',
    col.names = linebreak(names(dat_temp)),
    escape = FALSE
    ) |>
  kable_styling(c('striped', 'hover'),
                latex_options = 'HOLD_position'
                )
```



```{r}
# Student views per enrollee by item (bar chart)
dat_temp <- dat |>
  filter(Course.code %in% course_codes & User.role == 'Student') |>
  group_by(Citation) |>
  summarize(Views.per.enrollee = sum(Total.views) / max(Course.enrollment))
ggplot(dat_temp,
       aes(x = Views.per.enrollee,
           y = Citation
           )
       ) +
  geom_col(fill = colors_penn$primary[1]) +
  labs(title = 'Student views per enrollee',
       x = 'Views per enrollee'
       ) +
  geom_text(aes(label = round(Views.per.enrollee, 2)),
            color = 'white',
            hjust = +1
            ) +
  theme_classic()
```

We should discuss the calculation for views per enrollee (and whether there's a better approach) to ensure it makes sense. 

## Summary by term

```{r}
# Number of student views by term (table)
dat_temp <- dat |>
  filter(Course.code %in% course_codes & User.role == 'Student') |>
  group_by(Course.year, Course.term) |>
  summarize(Courses = length(unique(Course.code)),
            Items = length(unique(Citation)),
            'Maximum\nenrollment' = max(Course.enrollment),
            'Minimum\nenrollment' = min(Course.enrollment),
            'Files\ndownloaded' = sum(Files.downloaded),
            'File\nviews' = sum(File.views),
            'Full-text\nviews' = sum(Full.text.views),
            'All\nviews' = sum(Total.views)
            )
names(dat_temp)[c(1,2)] <- c('Course\nyear', 'Course\nterm')
kbl(dat_temp,
    format = 'latex',
    caption = 'Number of student views by term',
    col.names = linebreak(names(dat_temp)),
    escape = FALSE
    ) |>
  kable_styling(c('striped', 'hover'),
                latex_options = 'HOLD_position'
                )
```

```{r}
# Student views per citation by term (bar chart)
dat_temp <- dat |>
  filter(Course.code %in% course_codes & User.role == 'Student') |>
  group_by(Course.year, Course.term) |>
  summarize(Views.per.citation = sum(Total.views) / length(unique(Citation)))
ggplot(dat_temp,
       aes(x = Views.per.citation,
           y = paste(Course.year, Course.term)
           )
       ) +
  geom_col(fill = colors_penn$primary[1]) +
  labs(title = 'Student views per citation',
       x = 'Views per citation',
       y = 'Term'
       ) +
  geom_text(aes(label = round(Views.per.citation, 2)),
            color = 'white',
            hjust = +1
            ) +
  theme_classic()
```

We should discuss these calculations too.
