---
title: "Course Reserves Statistics"
author: "Lippincott Library"
date: today
execute: 
  echo: false
  warning: false
  error: false
opts_chunk: 
    R.options: 
    knitr.table.html.attr: "quarto-disable-processing=true"
format:
  pdf:
    mainfont: "Arial"
    sansfont: "Arial"
    monofont: "Courier New"
    include-in-header:
      text: |
        \usepackage{caption}
        \captionsetup[table]{labelformat=empty}
        \captionsetup[figure]{labelformat=empty}
fig-cap-location: top
---

```{r}
# Install (if needed) and load packages 
for(package in c('data.table', 'dplyr', 'tidyr', 'kableExtra', 'readr', 'readxl', 'stringr')){
  if( !(package %in% installed.packages()) ){
    install.packages(package)
  }
  eval(call('library', as.name(package)))
}
rm(package)

# Penn colors
colors_penn <- list(primary = c('#011f5b', '#990000'),
                    secondary = c('#3479be', '#faa755', '#bbd86b', '#bd60a5'),
                    gray = c('#555d6a', '#757f8f', '#a7aeba', '#e1e4ec'))
```

```{r}
# Load and join data (use data files with only relevant course codes)

setwd('~/GitHub/course-reserves-stats/res/')
data_file_metridoc <- 'leganto-usage-views-2026-03-17.csv'
data_file_alma <- c('alma_citations_20260624.xlsx') # Enter one or more file names

dat <-
  read_csv(data_file_metridoc,
           name_repair = 'universal',
           col_types = cols(.default = 'c',
                            Event.date = 'D',
                            Course.enrollment = 'n',
                            Files.downloaded = 'n',
                            File.views = 'n',
                            Full.text.views = 'n',
                            Total.views = 'n'
                            )
           ) |>
  filter(User.role == 'Student')

dat_alma <-
  lapply(data_file_alma,
         read_excel,
         .name_repair = 'universal',
         col_types = 'text'
         )
dat_alma <- do.call(rbind, dat_alma) |>
  select(Citation.ID,
         Chapter.Title,
         Citation.Title,
         Journal.Title,
         Material.type,
         Course.Code
         # ADD MORE ALMA FIELDS HERE!!
         ) |>
  unite(Title,
        Chapter.Title, Citation.Title, Journal.Title,
        sep = ', ',
        na.rm=TRUE) |>
  as.data.table()
dat_alma <- dat_alma[,
                     .(Course.Code = trimws(unlist(strsplit(Course.Code, ", ")))),
                     by = setdiff(names(dat_alma), 'Course.Code')]
dat_alma <- dat_alma[dat_alma$Course.Code %in% unique(dat$Course.code), ]

dat <- full_join(as.data.table(dat), dat_alma,
                 by = join_by(Citation == Citation.ID, Course.code == Course.Code),
                 #by = join_by(Citation == Citation.ID),
                 na_matches = 'never',
                 multiple = 'any'
                 ) |>
  rows_patch(unique(select(dat,
                           Course.year,
                           Course.term,
                           Academic.department,
                           Course.code,
                           Course.name,
                           Course.enrollment,
                           Course
                           )),
             by = c('Course.code'),
             unmatched = 'ignore'
             )
dat[is.na(dat$Total.views), c('Files.downloaded', 'File.views', 'Full.text.views', 'Total.views')] <- 0
# Escape characters that otherwise would break non-escaped kableExtra tables
dat$Title <- gsub('&', '\\\\&', dat$Title) 

rm(dat_alma, data_file_metridoc, data_file_alma)
```

```{r}
# Create functions

ttl_trunc <- function(df){
  str_trunc(df$Title, width = 37)
}

make.table <- function(df){
  kbl(df,
    format = 'latex',
    col.names = linebreak(names(dat_temp)),
    escape = FALSE,
    longtable = TRUE
    ) |>
  kable_styling(c('striped'),
                latex_options = c('HOLD_position', 'repeat_header')
                )
}
```

```{r}
# Concatenate key course terms
dat_temp <- drop_na(dat)
term_min <- paste(dat_temp$Course.term[dat_temp$Event.date == min(dat_temp$Event.date)][1],
                  dat_temp$Course.year[dat_temp$Event.date == min(dat_temp$Event.date)][1])
term_max <- paste(dat_temp$Course.term[dat_temp$Event.date == max(dat_temp$Event.date)][1],
                  dat_temp$Course.year[dat_temp$Event.date == max(dat_temp$Event.date)][1])
```

This report covers courses from `{r} if (term_max == term_min) term_min else paste(term_min, "through", term_max)`. It includes only courses that had course reserves views or downloads.

## Summary by item

```{r}
#| tbl-cap: "Number of views for each item"
dat_temp <- dat |>
  group_by(Title) |>
  summarize(Courses = length(unique(Course.code)),
            'Median\nenrollment' = median(Course.enrollment),
            Views = sum(Total.views)
            ) |>
  arrange(Title)
dat_temp$Title <- ttl_trunc(dat_temp)
make.table(dat_temp)
```

```{r}
# Prepare view rates
dat_rate <- dat |>
  group_by(Title, Course.code) |>
  summarize(Enrollment = median(Course.enrollment),
            Views = sum(Total.views)
            ) |>
  group_by(Title) |>
  summarize(Courses = length(unique(Course.code)),
            'Median\nenrollment' = median(Enrollment),
            Views = sum(Views),
            Students = sum(Enrollment),
            'Views per\nstudent' = round(sum(Views) / sum(Enrollment), 2)
            ) |>
  arrange(desc(`Views per\nstudent`), .by_group = FALSE)
ct_under_1 <- nrow(dat_rate |> filter(`Views per\nstudent` < 1 | Views == 0))
show_ct_under_1 <- ct_under_1 > 0
```

```{r}
#| tbl-cap: "Most-viewed and least-viewed items"
dat_temp <- dat_rate
if(nrow(dat_temp) > 10){
  dat_temp <- rbind(dat_temp[1:5, ],
                    rep("...", ncol(dat_temp)),
                    dat_temp[(nrow(dat_temp)-4):nrow(dat_temp), ]
                    )
}
dat_temp$Title <- ttl_trunc(dat_temp)
make.table(dat_temp)
```

Out of `{r} nrow(dat_rate)` `{r} if (nrow(dat_rate) == 1) "item" else "items"`, `{r} ct_under_1` `{r} if (ct_under_1 == 1) "item" else "items"` averaged below one view per student.

```{r}
#| include: !expr show_ct_under_1
#| tbl-cap: "Under-viewed items"
dat_temp <- dat_rate |> filter(`Views per\nstudent` < 1 | Views == 0)
if(nrow(dat_temp) == 0){
  dat_temp <- rbind(dat_temp,
                    rep("N/A", ncol(dat_temp))
                    )
}
dat_temp$Title <- ttl_trunc(dat_temp)
make.table(dat_temp)
```

## Summary by term

```{r}
#| tbl-cap: "Number of views by term"
dat_temp <- drop_na(dat) |>
  group_by(Course.year, Course.term) |>
  summarize(Courses = length(unique(Course.code)),
            'Median\nenrollment' = median(Course.enrollment),
            'Viewed\nitems' = length(unique(Citation)),
            Views = sum(Total.views)
            ) |>
  arrange(Course.year, Course.term)
names(dat_temp)[c(1,2)] <- c('Course\nyear', 'Course\nterm')
make.table(dat_temp)
```

{{< pagebreak >}}

## Views by date (as needed)

```{r}
# Presets for histogram (hard-coded)
presets <- list(
  Term = c('Spring'),
  Year = c('2025'),
  Event = as.Date(c('2025-04-05'))
)
```

```{r}
#| fig-cap: "Number of views by date"
if( !("ggplot2" %in% installed.packages()) ){
  install.packages("ggplot2")
}
library(ggplot2)

dates <- data.frame(Event.date = seq(from = as.Date(min(dat$Event.date, na.rm = TRUE)),
                                     to = as.Date(max(dat$Event.date, na.rm = TRUE)),
                                     by = "day"))
dat_temp <- drop_na(dat) |>
  filter(Course.term %in% presets$Term & Course.year %in% presets$Year) |>
  group_by(Event.date) |>
  summarize(Views = sum(Total.views))
dat_temp$Event.date <- as.Date(dat_temp$Event.date)
dat_temp <- left_join(dates, dat_temp) |> mutate_if(is.numeric, coalesce, 0)

ggplot(dat_temp,
       aes(x = Event.date,
           y = Views
           )
       ) +
  geom_col(fill = colors_penn$primary[1]) +
  geom_vline(xintercept = presets$Event,
             color = colors_penn$primary[2],
             linetype = "dashed",
             linewidth = .5
             ) +
  annotate('text',
           label = presets$Event,
           color = colors_penn$primary[2],
           x = presets$Event,
           y = Inf,
           hjust = "top",
           vjust = "bottom",
           angle = 90
           ) +
  labs(x = 'Date') +
  theme_classic(base_family = "sans")
```

